---
name: Docker
on:
  push:
    branches: [master]
  pull_request:
jobs:
  # build job
  build:
    name: Build
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: read
    strategy:
      fail-fast: false
      matrix:
        go: ["1.22"]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup docker QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          image=moby/buildkit:master
          network=host

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build docker image
      run: |
        make docker-buildx-build \
          DOCKER_BUILD_GO_VERSION=${{ matrix.go }} \
          DOCKER_BUILD_VERSION=$(git describe --always --tags --dirty --broken)-go${{ matrix.go }}
