---
name: Docker
on:
  push:
    branches: [master]
  pull_request:
jobs:
  # build job
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: read
    strategy:
      fail-fast: false
      matrix:
        go: ["1.22"]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        filter: tree:0

    - uses: actions/cache@v4
      with:
        path: |
          /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-docker-${{ hashFiles('**/go.sum') }}
          ${{ runner.os }}-docker-

    - name: Setup docker QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=moby/buildkit:master
          network=host

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build docker image
      run: |
        make docker-buildx-build \
          DOCKER_BUILD_GO_VERSION=${{ matrix.go }} \
          DOCKER_BUILD_VERSION=$(git describe --always --tags --dirty --broken)-go${{ matrix.go }}
